CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'USER',
    auth_source VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
    external_user_id VARCHAR(100),
    display_name VARCHAR(80),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    gameplay VARCHAR(160) NOT NULL,
    category VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    status_label VARCHAR(60) NOT NULL,
    online_count INTEGER NOT NULL DEFAULT 0,
    capacity INTEGER NOT NULL DEFAULT 0,
    address VARCHAR(255) NOT NULL,
    version VARCHAR(80) NOT NULL,
    pack VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    rules TEXT NOT NULL,
    icon VARCHAR(60) NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    maintenance BOOLEAN NOT NULL DEFAULT FALSE,
    last_checked_at TIMESTAMP WITH TIME ZONE,
    status_error VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(140) NOT NULL,
    kind VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    status_label VARCHAR(60) NOT NULL,
    server_slug VARCHAR(50) NOT NULL,
    time_text VARCHAR(255) NOT NULL,
    participation VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(60) NOT NULL,
    requires_pack BOOLEAN NOT NULL DEFAULT FALSE,
    priority INTEGER NOT NULL DEFAULT 0,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    title VARCHAR(180) NOT NULL,
    category VARCHAR(30) NOT NULL,
    category_label VARCHAR(80) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'PUBLISHED',
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    contact VARCHAR(160) NOT NULL,
    responsibilities VARCHAR(255) NOT NULL,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS wiki_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    title VARCHAR(140) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    icon VARCHAR(60) NOT NULL,
    link_url VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS history_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    title VARCHAR(160) NOT NULL,
    meta VARCHAR(255) NOT NULL,
    image_url VARCHAR(500),
    alt_text VARCHAR(255) NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    content TEXT NOT NULL,
    happened_at TIMESTAMP WITH TIME ZONE,
    published BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    kind VARCHAR(30) NOT NULL,
    name VARCHAR(80) NOT NULL,
    student_id VARCHAR(80),
    qq VARCHAR(30) NOT NULL,
    minecraft_id VARCHAR(40),
    reason TEXT,
    participant_count VARCHAR(40),
    purpose VARCHAR(120),
    expected_time VARCHAR(120),
    requirements TEXT,
    available_time VARCHAR(120),
    skill VARCHAR(120),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    admin_note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ideas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    nickname VARCHAR(80) NOT NULL,
    title VARCHAR(180) NOT NULL,
    category VARCHAR(40) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    public_reply TEXT,
    related_slug VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS idea_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idea_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_idea_like UNIQUE (idea_id, user_id)
);

CREATE TABLE IF NOT EXISTS activity_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_slug VARCHAR(80) NOT NULL,
    user_id BIGINT,
    minecraft_id VARCHAR(40) NOT NULL,
    qq VARCHAR(30) NOT NULL,
    admin_note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS private_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    body TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    admin_note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_user_id BIGINT NOT NULL,
    resource_type VARCHAR(40) NOT NULL,
    resource_id VARCHAR(80) NOT NULL,
    action VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_announcements_status_published ON announcements(status, published_at);
CREATE INDEX IF NOT EXISTS idx_activities_published_priority ON activities(published, priority);
CREATE INDEX IF NOT EXISTS idx_servers_published_status ON servers(published, status);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status, created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_status ON private_feedback(status, created_at);
