ALTER TABLE servers ADD COLUMN IF NOT EXISTS icon_media_id BIGINT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS icon_media_id BIGINT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS cover_media_id BIGINT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS content_blocks TEXT NOT NULL DEFAULT '[]';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS cover_media_id BIGINT;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS content_blocks TEXT NOT NULL DEFAULT '[]';
ALTER TABLE wiki_sections ADD COLUMN IF NOT EXISTS icon_media_id BIGINT;
ALTER TABLE wiki_sections ADD COLUMN IF NOT EXISTS content_blocks TEXT NOT NULL DEFAULT '[]';
ALTER TABLE history_items ADD COLUMN IF NOT EXISTS cover_media_id BIGINT;
ALTER TABLE history_items ADD COLUMN IF NOT EXISTS content_blocks TEXT NOT NULL DEFAULT '[]';

CREATE TABLE IF NOT EXISTS content_drafts (
    id VARCHAR(36) PRIMARY KEY,
    resource_type VARCHAR(30) NOT NULL,
    resource_id BIGINT,
    payload_json TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_content_draft_resource UNIQUE (resource_type, resource_id)
);

CREATE TABLE IF NOT EXISTS previous_content_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(30) NOT NULL,
    resource_id BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    saved_by BIGINT,
    saved_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_previous_content_version UNIQUE (resource_type, resource_id)
);

CREATE TABLE IF NOT EXISTS media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id VARCHAR(36),
    resource_type VARCHAR(30) NOT NULL,
    resource_id BIGINT,
    purpose VARCHAR(30) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    storage_name VARCHAR(255) NOT NULL UNIQUE,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER,
    height INTEGER,
    alt_text VARCHAR(255),
    caption VARCHAR(500),
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_content_drafts_resource ON content_drafts(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_draft ON media_assets(draft_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_media_assets_resource ON media_assets(resource_type, resource_id, deleted_at);
